### ISSUE TITLE
Phone() error

### ISSUE THREAD

**Issue by akchamczuk** [Regulus343/TetraText#2]
I am having a problem with your phone() function - 
echo phone(12345678901); throws following....
1. in TetraText.php line 421
   2.at HandleExceptions->handleError('2', 'Invalid argument supplied for foreach()', '/var/www/laravel/vendor/regulus/tetra-text/src/TetraText.php', '421', array('array' => null, 'formattedArray' => array(), 'object' => false)) in TetraText.php line 421
   3.at TetraText->camelizeKeys(null) in TetraText.php line 194
   4.at TetraText->phone('12345678901', array()) in Facade.php line 221
   5.at Facade::__callStatic('phone', array('12345678901', array())) in helpers.php line 65
   6.at Facade::phone('12345678901', array()) in helpers.php line 65
   7.at phone('12345678901') in KissNGoAppController.php line 42

Thanks.

**Comment by Regulus343** [comment]
I suspect you haven't updated the config file for the 0.6.x changes: https://github.com/Regulus343/TetraText/blob/master/src/config/format.php

Many new config variables were added for 0.6.0.

**Comment by akchamczuk** [comment]
I am running the latest 0.6.0.  Did a fresh install from composer and still giving same error.  I've tried other functions and they are working (eg money()).

**Comment by Regulus343** [comment]
Have you checked that the config file is indeed in config/format.php? You may have to run "php artisan vendor:publish" if it isn't. I do see that the readme makes no mention of that, so I will address that.

**Comment by akchamczuk** [comment]
That command did the trick! Thank-you.
